{"name": "test_mul[整数]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 2\n  +3\n  -2", "trace": "self = <pythoncode.pytest实战二.test_cal2.TestCal object at 0x000002416969ED60>, a = 1, b = 2, result = 3\nsetup_cal = <pythoncode.pytest实战一作业.cal_hw.Calculator object at 0x00000241695B40A0>\n\n    @pytest.mark.dependency(name='second')\n    @pytest.mark.run(order=3)\n    def test_mul(self, a, b, result,setup_cal):\n        print(\"乘法\")\n>       assert result == setup_cal.mul(a, b)\nE       assert 3 == 2\nE         +3\nE         -2\n\ntest_cal2.py:71: AssertionError"}, "parameters": [{"name": "a", "value": "1"}, {"name": "b", "value": "2"}, {"name": "result", "value": "3"}], "start": 1592415578668, "stop": 1592415578669, "uuid": "c6ea7e60-8866-45fb-83a8-d2ad78e83024", "historyId": "19f994944b456c7c06d01557b42caa08", "testCaseId": "a16c2fd40efa95385dce294770cabffe", "fullName": "test_cal2.TestCal#test_mul", "labels": [{"name": "tag", "value": "dependency(name='second')"}, {"name": "tag", "value": "run(order=3)"}, {"name": "suite", "value": "test_cal2"}, {"name": "subSuite", "value": "TestCal"}, {"name": "host", "value": "DESKTOP-UGIE581"}, {"name": "thread", "value": "8584-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cal2"}]}